services:
  - type: web
    name: Brian-XD
    env: node
    plan: free
    repo: https://github.com/briantechspace/Brian-XD
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
